# coding: utf-8

"""
    XKCD

    Webcomic of romance, sarcasm, math, and language.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from xkcd_python_sdk import Xkcd

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        xkcd = Xkcd(
        )
        self.assertIsNotNone(xkcd)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
