# coding: utf-8

# flake8: noqa

"""
    XKCD

    Webcomic of romance, sarcasm, math, and language.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.0"

# import ApiClient
from xkcd_python_sdk.api_client import ApiClient

# import Configuration
from xkcd_python_sdk.configuration import Configuration

# import exceptions
from xkcd_python_sdk.exceptions import OpenApiException
from xkcd_python_sdk.exceptions import ApiAttributeError
from xkcd_python_sdk.exceptions import ApiTypeError
from xkcd_python_sdk.exceptions import ApiValueError
from xkcd_python_sdk.exceptions import ApiKeyError
from xkcd_python_sdk.exceptions import ApiException

from xkcd_python_sdk.client import Xkcd
