# coding: utf-8
"""
    XKCD

    Webcomic of romance, sarcasm, math, and language.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from xkcd_python_sdk.client_custom import ClientCustom
from xkcd_python_sdk.configuration import Configuration
from xkcd_python_sdk.api_client import ApiClient
from xkcd_python_sdk.type_util import copy_signature
from xkcd_python_sdk.apis.tags.info_api import InfoApi



class Xkcd(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.info: InfoApi = InfoApi(api_client)
