# coding: utf-8

"""
    XKCD

    Webcomic of romance, sarcasm, math, and language.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import xkcd_python_sdk
from xkcd_python_sdk.model.comic import Comic
from xkcd_python_sdk import configuration


class TestComic(unittest.TestCase):
    """Comic unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
