# coding: utf-8

"""
    XKCD

    Webcomic of romance, sarcasm, math, and language.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from xkcd_python_sdk.paths.comic_id_info_0_json.get import GetByIdRaw
from xkcd_python_sdk.paths.info_0_json.get import GetComicMetadataRaw


class InfoApiRaw(
    GetByIdRaw,
    GetComicMetadataRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
