# coding: utf-8

"""
    XKCD

    Webcomic of romance, sarcasm, math, and language.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from xkcd_python_sdk.paths.comic_id_info_0_json.get import GetById
from xkcd_python_sdk.paths.info_0_json.get import GetComicMetadata
from xkcd_python_sdk.apis.tags.info_api_raw import InfoApiRaw


class InfoApi(
    GetById,
    GetComicMetadata,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: InfoApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = InfoApiRaw(api_client)
