# coding: utf-8

"""
    XKCD

    Webcomic of romance, sarcasm, math, and language.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import xkcd_python_sdk
from xkcd_python_sdk.paths.comic_id_info_0_json import get
from xkcd_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestComicIdInfo0Json(ApiTestMixin, unittest.TestCase):
    """
    ComicIdInfo0Json unit test stubs
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
